name: ShellCheck Linter

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv
          sudo mv shellcheck-*/shellcheck /usr/local/bin/

      - name: Run ShellCheck
        run: |
          find . -type f \( -exec grep -qE '^#!.*bash' {} \; -o -exec grep -qE '^#!.*sh' {} \; \) -not -path "./.git/*" -print0 | xargs -0 shellcheck --external-sources --severity=warning